apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-php
    entorno: dev
  name: hello-php-healthcheck-error
spec:
  containers:
    - image: tecnocrata/hello-php:error
      name: hello-php
      ports:
        - containerPort: 80
          name: app-port
      resources: {}
      livenessProbe: # Is it live? if it is not restart pod
        httpGet:
          path: /
          port: app-port
      readinessProbe: # Is it ready to receive traffic?
        httpGet:
          path: /
          port: app-port

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
