apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-world
    entorno: dev
  name: hello-php
spec:
  containers:
    - image: tecnocrata/hello-php:2.3
      name: hello-world
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /tmp
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing
        # the files yo want to add to the container
        # each key is a file
        name: nginx-conf
  restartPolicy: Never
status: {}
