apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-initial-php-apps
    entorno: dev
    run: hello-php
  name: hello-php-for-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: my-initial-php-apps
    entorno: dev
    run: hello-php
  type: NodePort
status:
  loadBalancer: {}
