apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-initial-php-apps
  name: hello-php-clusterip-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: my-initial-php-apps
    entorno: dev
    run: hello-php
status:
  loadBalancer: {}
