apiVersion: v1
kind: Service
metadata:
  name: hello-php-clusterip-svc
  labels:
    mygroup: php-clusterip-svcs
spec:
  type: ClusterIP
  # Three types of ports for a service
  # nodePort - a static port assigned on each the node
  # port - port exposed internally in the cluster
  # targetPort - the container port to send requests to
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: my-initial-php-apps # this will group pods under service
