apiVersion: v1
kind: Service
metadata:
  name: hello-php-clusterip-svc
  labels:
    mygroup: php-clusterip-svcs
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: my-initial-php-apps # this will group pods under service
