apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-php
    entorno: dev
    app: my-initial-php-apps # this will group pods under service
  name: hello-php
spec:
  containers:
    - image: tecnocrata/hello-php:2.3
      name: hello-php
      ports:
        - containerPort: 80
          name: app-port
      resources: {}
      envFrom: # refering my-config configmap
        - configMapRef:
            name: my-config
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
