apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-php
    entorno: dev
    app: my-initial-php-apps # this will group pods under service
  name: hello-php
spec:
  containers:
    - image: tecnocrata/hello-php:2.3
      name: hello-php
      ports:
        - containerPort: 80
          name: app-port
      resources: {}
      env: # refering my-config configmap
        - name: SOME_VARIABLE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: someValue
        - name: VARIABLE2
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: propX
        - name: ERROR_LEVEL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: example.property1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
